---
title: \textbf{Taller 3}
author: Paula Amado y David Acero
output:
  pdf_document:
    latex_engine: xelatex
    number_sections: true
    toc_depth: 2
fontsize: 12pt
header-includes:
  \usepackage[T1]{fontenc}
  \usepackage{babel}
  \usepackage{float}
  \floatplacement{figure}{H}
  \usepackage{array}
  \usepackage{makecell}
  \usepackage{fancyhdr}
  \usepackage{graphicx}
  \usepackage{longtable}
  \usepackage{hyperref}
  \usepackage{fontspec}
  \usepackage{booktabs}
  \setmainfont[
    BoldFont={arialbd.ttf}, 
    ItalicFont={ariali.ttf},
    BoldItalicFont={arialbi.ttf}
    ]{arial.ttf}
  \usepackage{caption} 
  \captionsetup[table]{skip=10pt}
  \usepackage{titling}
  \usepackage{tabularx}
  \usepackage{titlesec}
  \setlength{\headheight}{60pt}
always_allow_html: yes
geometry: "left=3cm,right=3cm,top=2cm,bottom=4cm"
---


```{r setup, include=FALSE,warning=FALSE,message=FALSE,echo=FALSE}

library(openxlsx)
library(readxl)
library(sf)
library(leaflet)
library(dplyr)
library(viridis)
library(tidyverse)
library(tidyverse)
library(tidytext)
library(broom)
library(randomForest)
library(raster)
library(caret)
library(pacman)
library(nnet)

options(scipen = 999)

knitr::opts_chunk$set(echo = TRUE)

```


\section{Introducción} 
Una nueva start-up en el sector inmobiliario busca establecer una estrategia sólida para la compra y venta de propiedades en Chapinero, Bogotá. Su principal objetivo es adquirir la mayor cantidad de inmuebles en esta zona estratégica mientras optimiza los costos y minimiza los riesgos. Para ello, han solicitado el desarrollo de un modelo predictivo que permita tomar decisiones fundamentadas y maximizar el rendimiento de sus inversiones.

Uno de los desafíos más significativos es la falta de información detallada sobre las propiedades en Chapinero, lo que dificulta la estimación precisa de precios y la definición de estrategias efectivas. Además, la empresa está alerta ante los riesgos asociados al uso de modelos predictivos en el sector, recordando casos como el de Zillow, donde la sobreestimación de precios derivó en pérdidas millonarias y un impacto negativo en su operación. Este proyecto busca superar tales desafíos mediante el desarrollo de un modelo robusto, adaptado a las limitaciones de datos, que garantice predicciones confiables y facilite una toma de decisiones eficiente y sostenible.

La literatura existente subraya la relevancia de aplicar enfoques avanzados de machine learning para mejorar la precisión en la predicción de precios de vivienda. Por ejemplo, Truong et al. (2020) destacaron cómo técnicas como la regresión híbrida y la generalización apilada combinan estrategias como Random Forest, XGBoost y LightGBM para manejar datos complejos, reducir errores y equilibrar el sesgo y la varianza en los modelos. Estas metodologías resultan clave para prevenir errores costosos y asegurar resultados sostenibles.

Por su parte, Adetunji et al. (2022) demostraron que el algoritmo Random Forest es particularmente eficaz para predecir precios de viviendas al considerar factores como ubicación, tamaño y condiciones físicas. Asimismo, investigaciones como las de Varma et al. (2018) han explorado las ventajas de combinar diferentes métodos de predicción para obtener estimaciones más precisas. Inspirados en estos avances, este proyecto aprovechará los conocimientos existentes para construir un modelo predictivo que se ajuste de manera óptima al contexto de Chapinero y sus particularidades.  


\section{Datos}
\section{Modelos y resultados} 
\section{Conclusiones y recomendaciones}
\section{Referencias}

\begin{itemize}
  \item Adetunji, A. B., Akande, O. N., Ajala, F. A., Oyewo, O., Akande, Y. F., & Oluwadara, G. (2021). House price prediction using random forest machine learning technique. Procedia Computer Science, 199, 806–813. 
  \item Varma, A., Sarma, A., Doshi, S., & Nair, R. (2018). House price prediction using machine learning and neural networks. 
  \item Truong, Q., Nguyen, M., Dang, H., & Mei, B. (2020). Housing price prediction via improved machine learning techniques. Procedia Computer Science, 174, 433–442. 
\end{itemize}




